### ISSUE TITLE
[py2py3] test str/bytes use in WMCore (wildcard issue)

### ISSUE THREAD

**Issue by mapellidario** [dmwm/WMCore#10323]
**Impact of the bug**

It should involve `src/python/WMCore/MicroService/DataStructs/MSRuleCleanerWflow.py` only

**Describe the bug**
We have not observed any bug at the moment, but this is very likely to create some problems.

(add here all the checks about str/bytes that did not fell into another issue)

- [ ]  `MicroService/DataStructs/MSRuleCleanerWflow.py` 

    In #10307 we made the following changes

    ```python
    -                elif (isinstance(data['type'], tuple) and (str in data['type'] or unicode in data['type'])) or \
    -                     (data['type'] is str or data['type'] is unicode):
    +               elif (isinstance(data['type'], tuple) and (bytes in data['type'] or str in data['type'])) or \
    +                    (data['type'] is bytes or data['type'] is str):
    ```

- [ ] #10321 `src/python/WMCore/JobStateMachine/ChangeState.py`
- [ ] #10321 `src/python/WMCore/WMSpec/WMTask.py`
- [ ] #10329 `src/python/WMCore/WMRuntime/Scripts/SetupCMSSWPset.py`

**Expected behavior**
These are supposed to behave the same in py2 and py3 as he previous lines, but there is a somewhat high probability that they will not. We should make sure that these lines behave properly when we have a py3 environment.

**Comment by amaltaro** [comment]
The 4 modules mentioned above have all been tested and are already in production as well. I think it's safe to close this issue, and if a problem is found in the near future, we can always either reopen it or create a new specific issue.
Closing it.
