### ISSUE TITLE
[py2py3] effect of py3 round, mostly on job splitting

### ISSUE THREAD

**Issue by mapellidario** [dmwm/WMCore#10354]
**Impact of the bug**

Py3 `round` behaves differently than from py2 one. This may affect Job Splitting.

**Describe the bug**

We have not observed any bug at the moment, but we should keep an eye out and be sure that this does not cause any problem to us.

The differences are reported [here](https://docs.python.org/3/whatsnew/3.0.html#builtins), while a good description of the impact of the problem is available [here](https://kingant.net/2019/01/rounding-numbers-in-python-2-and-python-3/).

**How to reproduce it**

```plaintext
Python 2.7.13+ (default, Jan 22 2021, 17:43:09) 
[GCC 6.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> round(100.5)
101.0 # float, rounded up
>>> round(101.5)
102.0 # float, rounded up
```

```plaintext
Python 3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> round(100.5)
100 # int, rounded down
>>> round(101.5)
102 # int, rounded up
```

- [ ] (should be safe) #10319, #10379 `src.python.WMCore.MicroService.Tools.Common`
- [ ] (should be safe) #10319, #10379 `src.python.WMCore.MicroService.MSMonitor.MSMonitor`
- [ ] (should be safe) #10362 
- [ ] #10331
  - `src.python.WMCore.JobSplitting.LumiBased`
  - `src.python.WMCore.JobSplitting.EventAwareLumiBased`
  -  `src.python.WMCore.JobSplitting.FileBased`
- [ ] #10295 #10440
  - `src.python.WMCore.Services.LogDB.LogDBBackend`
- [ ] #10284 #10440
  - `src.python.WMCore.JobSplitting.EventAwareLumiByWork`
- [ ] `src/python/WMCore/WMSpec/StdSpecs/StdBase.py`, https://github.com/dmwm/WMCore/blob/bb573b442a53717057c169b05ae4fae98f31063b/src/python/WMCore/WMSpec/StdSpecs/StdBase.py#L115

**Expected behavior**

We should make sure that WMCore is aware and compliant with this new behavior of `round`.

**Comment by amaltaro** [comment]
Thanks for creating this detailed issue with a check list, Dario.

I didn't check every single of those, but I consider the validation done with central services and python3 WMAgent (1.5.2) good enough. With all the templates we have, I believe all this code has already been exercised. I think it's safe to close it now.
