### ISSUE TITLE
[py2py3] check the use of str/bytes in formatting dictionary keys

### ISSUE THREAD

**Issue by mapellidario** [dmwm/WMCore#10377]
**Impact of the bug**
WMCore in general

**Describe the bug**

 We have not observed any bug at the moment, but this is likely to create some problems.

In python3, `str` and `bytes` are hashed to different values and they can not be used interchangeably when formatting dictionary keys:

```plaintext
Python 2.7.18 (default, Mar  9 2021, 11:09:26) 
>>> ciao = {"hello":1, "world":2}
>>> ciao[b'hello']
1
>>> ciao[u'hello']
1 
```

```
Python 3.9.2 (default, Feb 28 2021, 17:03:44) 
>>> ciao = {"hello":1, "world":2}
>>> ciao['hello']
1
>>> ciao[b'hello']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: b'hello'
```

This may cause problems if and where we implicitly rely on py2 automatic conversion of bytes to unicode, for example in
- [ ] `src/python/WMCore/WMSpec/StdSpecs/StdBase.py`, #10362 
- [ ] `src/python/WMCore/WMSpec/StdSpecs/TaskChain.py` #10362 
- [ ] `src/python/WMComponent/TaskArchiver/CleanCouchPoller.py`, #10371  
- [ ] `src/python/WMCore/ACDC/DataCollectionService.py` #10284 
- [ ] `src/python/WMCore/JobSplitting/EventAwareLumiByWork.py` #10284 
- [ ] `src/python/WMCore/WebTools/RESTApi.py`: #10284 
- [ ] `src/python/WMCore/JobSplitting/LumiBased.py` : #10331 

We should make sure that we catch all the aforementioned changes do not cause issues to us.

**Expected behavior**
We should make sure that we are consistent in how we format objects to create dictionary keys.

**Comment by amaltaro** [comment]
Besides:
```
src/python/WMCore/WebTools/RESTApi.py
```

all the rest has been validated, either with central services or with the agent, and there are no known issues. The RESTApi is likely going to be used only by CRABServer, and if needed we can either reopen this issue or create a new and specific one.

Thanks for creating this extra validation issue, Dario. Closing it now.
