### ISSUE TITLE
[Meta-issue] Unified way to manage pileup datasets/locations being used in central production

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#9779]
**Impact of the new feature**
ReqMgr2 / ReqMgr2MS

**Is your feature request related to a problem? Please describe.**
Not really from a problem, but looking for a better way to manage workflows and the pileup datasets required by central production activities.

At the moment, pileup datasets get defined within every single production campaign, they might contain specific locations as well, which is supposed to reflect where that dataset is currently available at. This seems to add unnecessary complexity to the system, with campaigns having multiple pileups, e.g.:
https://cmsweb.cern.ch/couchdb/_utils/document.html?reqmgr_auxiliary/CAMPAIGN_CONFIG_RunIIAutumn18DR

with having the same pileup dataset in different campaigns (and potentially with different locations), which can also mean that some of those pileup datasets might be replicated more than what we can afford (or wanted to).

**Describe the solution you'd like**
So, the solution I propose here is to have a unified view of the pileup datasets being used in production, as well as their current location on the grid, and the expected places that they should be available. This could be extended to other parameters as well, like number of replicas of the dataset, list of campaigns meant to use it, etc.

This is a meta-issue and it depends on the following GH issues:

- [x]  [MS] Create a new microservice skeleton called MSPileup #11423 
- [x]  [MS] Create monitoring dashboard for MSPileup microservice #11429 
- [x]  [MS] Define a MSPileup pileup data structure to be persisted in the database #11424 
- [x]  [MS] Define MSPileup RESTful endpoint and actions for pileup data #11425 
- [x]  [MS] Define MSPileup logic for data placement, monitoring and removal #11426 
- [x]  [MS] Update MSTransferor to start consuming the MSPileup information #11427 
- [x]  [MS] Remove all the pileup rule removal logic from MSRuleCleaner #11428 
- [x] [MS] Fix document validation response and GET documents #11511
- [x] [MS] Setup proper mandatory/optional values for MSPileup document #11498 
- [x] [MS] Manage auth/authz rules for MS services #11465
- [x]  MSPileup: track existent rule ids in the document ruleIds field #11544
- [x] [MS] update to the pileup active state should trigger a timestamp update #11546
- [x] [MS] Premature deletion of pileup documents in the cleanup task #11547

**Describe alternatives you've considered**
keep using whatever we have

**Additional context**
none

**Comment by vkuznet** [comment]
@amaltaro , could you please provide technical details how to address this issue, i.e. translate from your plain english description into set of actions which should be applied in a code base. Once I'll have better understanding which system, components, code base should be used and where changes should go I can start working on this issue.

**Comment by amaltaro** [comment]
And we have just completed all the 13 tasks that were planned while conceiving this new microservice. Thank you very much @vkuznet! Closing this meta-issue out.
